name: "Chunk difference"
on:
  pull_request:
  # push:

jobs:
  build-source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci
      working-directory: ./apps/app
    - name: Build
      run: npm run build
      working-directory: ./apps/app
    - name: Copy stats for current build
      uses: actions/upload-artifact@v1
      with:
        name: stats-source
        path: ./apps/app/dist/stats.json

  build-target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.base_ref }}
    - name: Install dependencies
      run: npm ci
      working-directory: ./apps/app
    - name: Build
      run: npm run build
      working-directory: ./apps/app
    - name: Copy stats for current build
      uses: actions/upload-artifact@v1
      with:
        name: stats-target
        path: ./apps/app/dist/stats.json

  compare:
    runs-on: ubuntu-latest
    needs: [build-source, build-target]
    steps:
    - uses: actions/checkout@v1
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: stats-source
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: stats-target
    - name: Diff
      run: |
        diff=`npx webpack-stats-diff ./stats-target/stats.json ./stats-source/stats.json`
        echo $diff
        echo $diff > diff.txt
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.context.issue.number || steps.findPr.outputs.pr }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown**
          - Created by [create-or-update-comment][1]

          [1]: https://github.com/peter-evans/create-or-update-comment
    # - name: Print values
    #   shell: bash
    #   run: |
    #     value=`cat ./apps/app/dist/stats.json`
    #     echo The result is $value

    # - uses: jwalton/gh-find-current-pr@v1
    #   id: findPr
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    # # This will echo "Your PR is 7", or be skipped if there is no current PR.
    # - run: echo "Your PR is ${PR}"
    #   if: success() && steps.findPr.outputs.number
    #   env:
    #     PR: ${{ steps.findPr.outputs.pr }}
    # - uses: ./
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     pull_request: ${{ steps.findPr.outputs.pr }}
